In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
part_d = pd.read_csv("provider_data/partd/Part-D.csv",encoding='ISO-8859-1',low_memory=False)
leie_ex = pd.read_csv("provider_data/LEIE_Exclusion.csv",encoding='ISO-8859-1',low_memory=False)

In [3]:
part_d

,PRSCRBR_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_MI,Prscrbr_Crdntls,Prscrbr_Gndr,Prscrbr_Ent_Cd,Prscrbr_St1,Prscrbr_St2,Prscrbr_City,...,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Dual_Cnt,Bene_Ndual_Cnt,Bene_Avg_Risk_Scre
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,M,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,...,49.0,67.0,27.0,NaN,NaN,0.0,NaN,28.0,78.0,2.245800
1,1003000142,Khalil,Rashid,NaN,M.D.,M,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,...,82.0,130.0,81.0,NaN,12.0,0.0,NaN,125.0,103.0,1.695165
2,1003000167,Escobar,Julio,E,DDS,M,I,5 Pine Cone Rd,NaN,Dayton,...,23.0,41.0,0.0,0.0,NaN,0.0,NaN,0.0,43.0,1.006070
3,1003000175,Reyes-Vasquez,Belinda,NaN,D.D.S.,F,I,322 N Azusa Ave Ste 202,NaN,La Puente,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.251869
4,1003000282,Blakemore,Rosie,K,FNP,F,I,Tennessee Prison For Women,3881 Stewarts Lane,Nashville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.919074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255170,1992999569,Yuen,Jenny,F,"O.D., F.A.A.O",F,I,515 Gough St,NaN,San Francisco,...,NaN,NaN,0.0,16.0,0.0,0.0,NaN,NaN,NaN,1.451353
1255171,1992999650,Yong,Wayne,B,DMD,M,I,28 Atlantic Avenue,121,Boston,...,13.0,NaN,NaN,18.0,0.0,0.0,NaN,NaN,NaN,1.344691
1255172,1992999759,Soriano,Dino,V,RN MSN HSA FNP-C,M,I,171 Clover Point Cir,NaN,Guyton,...,NaN,16.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,1.545349
1255173,1992999825,Deschenes,Geoffrey,R,M.D.,M,I,1100 9th Ave,Ms:m4-Pfs,Seattle,...,62.0,100.0,NaN,16.0,NaN,0.0,NaN,18.0,108.0,1.109445
1255174,1992999874,Joffe,Gabriella,NaN,NaN,F,I,5620 Brook Rd,NaN,Richmond,...,51.0,74.0,25.0,NaN,NaN,0.0,NaN,28.0,75.0,2.748669

In [4]:
part_d.columns

Index(['PRSCRBR_NPI', 'Prscrbr_Last_Org_Name', 'Prscrbr_First_Name',
       'Prscrbr_MI', 'Prscrbr_Crdntls', 'Prscrbr_Gndr', 'Prscrbr_Ent_Cd',
       'Prscrbr_St1', 'Prscrbr_St2', 'Prscrbr_City', 'Prscrbr_State_Abrvtn',
       'Prscrbr_State_FIPS', 'Prscrbr_zip5', 'Prscrbr_RUCA',
       'Prscrbr_RUCA_Desc', 'Prscrbr_Cntry', 'Prscrbr_Type',
       'Prscrbr_Type_src', 'Tot_Clms', 'Tot_30day_Fills', 'Tot_Drug_Cst',
       'Tot_Day_Suply', 'Tot_Benes', 'GE65_Sprsn_Flag', 'GE65_Tot_Clms',
       'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst', 'GE65_Tot_Day_Suply',
       'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes', 'Brnd_Sprsn_Flag',
       'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst', 'Gnrc_Sprsn_Flag',
       'Gnrc_Tot_Clms', 'Gnrc_Tot_Drug_Cst', 'Othr_Sprsn_Flag',
       'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst', 'MAPD_Sprsn_Flag',
       'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst', 'PDP_Sprsn_Flag', 'PDP_Tot_Clms',
       'PDP_Tot_Drug_Cst', 'LIS_Sprsn_Flag', 'LIS_Tot_Clms', 'LIS_Drug_Cst',
       'NonLIS_Sprsn_Flag', 'NonLIS_Tot_Clms', 'NonLIS_Drug_Cst',
       'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
       'Opioid_Tot_Benes', 'Opioid_Prscrbr_Rate', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply', 'Opioid_LA_Tot_Benes',
       'Opioid_LA_Prscrbr_Rate', 'Antbtc_Tot_Clms', 'Antbtc_Tot_Drug_Cst',
       'Antbtc_Tot_Benes', 'Antpsyct_GE65_Sprsn_Flag',
       'Antpsyct_GE65_Tot_Clms', 'Antpsyct_GE65_Tot_Drug_Cst',
       'Antpsyct_GE65_Bene_Suprsn_Flag', 'Antpsyct_GE65_Tot_Benes',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_Api_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_Natind_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_Avg_Risk_Scre'],
      dtype='object')

In [5]:
part_d = part_d.dropna(subset=["PRSCRBR_NPI"],axis=0)
part_d = part_d.dropna(subset=["Prscrbr_Last_Org_Name"],axis=0)
part_d = part_d.dropna(subset=["Prscrbr_First_Name"],axis=0)

In [6]:
leie_ex = leie_ex.dropna(subset=["NPI"],axis=0)
ex_npi = leie_ex[leie_ex["NPI"]!=0]["NPI"]
ex_lnames = leie_ex.dropna(subset=["LASTNAME"],axis=0)["LASTNAME"]
ex_fnames = leie_ex.dropna(subset=["FIRSTNAME"],axis=0)["FIRSTNAME"]
leie_ex["MIDNAME"] = leie_ex["MIDNAME"].apply(lambda row : row if row!= " " else 0)
ex_mi = leie_ex[leie_ex["MIDNAME"]!=0]["MIDNAME"]

In [7]:
print(leie_ex.shape)
print(part_d.shape)

(76546, 18)
(1255124, 85)

In [8]:
# 7 hrs Processing Time
x = part_d["PRSCRBR_NPI"].size
count = 0
y =[];
while (count < x):
    chk = part_d["PRSCRBR_NPI"].iloc[count]
    chk1 = part_d["Prscrbr_First_Name"].iloc[count]
    chk2 = part_d["Prscrbr_Last_Org_Name"].iloc[count]
    if(chk in ex_npi.unique()):
        y.append(1)
    elif chk1 in ex_fnames.unique():
         y.append(1)
    elif chk2 in ex_lnames.unique():
         y.append(1)  
    else:
        y.append(0)
    count = count+1

partdx = pd.DataFrame(y, columns =['Fraud'])
print(partdx.value_counts())
x=partdx.size
c=0
part_d["Fraud"]=partdx
while(c<x):
    part_d["Fraud"].iloc[c]=partdx["Fraud"].iloc[c]
    c=c+1

Fraud
0        1253630
1           1494
dtype: int64

In [9]:
part_d["Fraud"].value_counts()

0.0    1253630
1.0       1494
Name: Fraud, dtype: int64

In [10]:
part_d.to_csv("labelled_data/part_D/partd_data.csv")

In [11]:
part_d

,PRSCRBR_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_MI,Prscrbr_Crdntls,Prscrbr_Gndr,Prscrbr_Ent_Cd,Prscrbr_St1,Prscrbr_St2,Prscrbr_City,...,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Dual_Cnt,Bene_Ndual_Cnt,Bene_Avg_Risk_Scre,Fraud
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,M,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,...,67.0,27.0,NaN,NaN,0.0,NaN,28.0,78.0,2.245800,0.0
1,1003000142,Khalil,Rashid,NaN,M.D.,M,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,...,130.0,81.0,NaN,12.0,0.0,NaN,125.0,103.0,1.695165,0.0
2,1003000167,Escobar,Julio,E,DDS,M,I,5 Pine Cone Rd,NaN,Dayton,...,41.0,0.0,0.0,NaN,0.0,NaN,0.0,43.0,1.006070,0.0
3,1003000175,Reyes-Vasquez,Belinda,NaN,D.D.S.,F,I,322 N Azusa Ave Ste 202,NaN,La Puente,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.251869,0.0
4,1003000282,Blakemore,Rosie,K,FNP,F,I,Tennessee Prison For Women,3881 Stewarts Lane,Nashville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.919074,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255170,1992999569,Yuen,Jenny,F,"O.D., F.A.A.O",F,I,515 Gough St,NaN,San Francisco,...,NaN,0.0,16.0,0.0,0.0,NaN,NaN,NaN,1.451353,0.0
1255171,1992999650,Yong,Wayne,B,DMD,M,I,28 Atlantic Avenue,121,Boston,...,NaN,NaN,18.0,0.0,0.0,NaN,NaN,NaN,1.344691,0.0
1255172,1992999759,Soriano,Dino,V,RN MSN HSA FNP-C,M,I,171 Clover Point Cir,NaN,Guyton,...,16.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,1.545349,1.0
1255173,1992999825,Deschenes,Geoffrey,R,M.D.,M,I,1100 9th Ave,Ms:m4-Pfs,Seattle,...,100.0,NaN,16.0,NaN,0.0,NaN,18.0,108.0,1.109445,0.0
1255174,1992999874,Joffe,Gabriella,NaN,NaN,F,I,5620 Brook Rd,NaN,Richmond,...,74.0,25.0,NaN,NaN,0.0,NaN,28.0,75.0,2.748669,0.0