In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Import all the required DataSets

In [3]:
part_b = pd.read_csv("provider_data/partb/Part-B.csv",encoding='ISO-8859-1',low_memory=False)
leie_ex = pd.read_csv("provider_data/LEIE_Exclusion.csv",encoding='ISO-8859-1',low_memory=False)

## DATA PRE_PROCESSING -- PART-B (Medicare Physician & Other Practitioners)

In [4]:
part_b.head(10)

,ï»¿Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,...,Bene_CC_Dprssn_Pct,Bene_CC_Dbts_Pct,Bene_CC_Hyplpdma_Pct,Bene_CC_Hyprtnsn_Pct,Bene_CC_IHD_Pct,Bene_CC_Opo_Pct,Bene_CC_RAOA_Pct,Bene_CC_Sz_Pct,Bene_CC_Strok_Pct,Bene_Avg_Risk_Scre
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,M,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,...,35.00%,47.00%,73.00%,75.00%,66.00%,11.00%,51.00%,9.00%,19.00%,2.5028
1,1003000134,Cibull,Thomas,L,M.D.,M,I,2650 Ridge Ave,Evanston Hospital,Evanston,...,15.00%,20.0%,48.00%,48.00%,24.00%,10%,38.00%,1.0%,3.00%,1.1124
2,1003000142,Khalil,Rashid,NaN,M.D.,M,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,...,37.00%,35.00%,52.00%,68.00%,31.00%,NaN,75.00%,NaN,NaN,1.6935
3,1003000423,Velotta,Jennifer,A,M.D.,F,I,11100 Euclid Ave,NaN,Cleveland,...,27.00%,NaN,52.00%,50.0%,23.00%,20.0%,32.00%,0%,NaN,0.7089
4,1003000480,Rothchild,Kevin,B,MD,M,I,12605 E 16th Ave,NaN,Aurora,...,43.00%,39.00%,43.00%,60.0%,33.00%,13.00%,57.00%,NaN,NaN,2.1137
5,1003000522,Weigand,Frederick,J,MD,M,I,1565 Saxon Blvd,Suite 102,Deltona,...,14.00%,34.00%,75.00%,75.00%,37.00%,10%,52.00%,NaN,5.00%,1.2401
6,1003000530,Semonche,Amanda,M,DO,F,I,1021 Park Ave,Suite 203,Quakertown,...,28.00%,24.00%,73.00%,69.00%,23.00%,8.00%,32.00%,NaN,NaN,1.1437
7,1003000597,Kim,Dae,Y,"M.D., PH.D",M,I,1145 S Utica Ave,Suite 202,Tulsa,...,26.00%,42.00%,65.00%,75.00%,47.00%,5.00%,46.00%,2.00%,7.00%,1.6750
8,1003000639,Benharash,Peyman,NaN,MD,M,I,10833 Leconte Ave Room 62-215,NaN,Los Angeles,...,38.00%,40.0%,75.00%,75.00%,75.00%,NaN,43.00%,NaN,NaN,2.3550
9,1003000704,Gatton,Zachary,M,M.D.,M,I,1330 Coshocton Ave,NaN,Mount Vernon,...,18.00%,36.00%,47.00%,71.00%,42.00%,NaN,53.00%,NaN,NaN,1.7588

In [5]:
part_b["Rndrng_NPI"] = part_b["ï»¿Rndrng_NPI"]
part_b=part_b.drop("ï»¿Rndrng_NPI",axis=1)

In [6]:
part_b = part_b.dropna(axis=0,thresh=2)
part_b = part_b.dropna(subset=["Rndrng_NPI"],axis=0)
part_b = part_b.dropna(subset=["Rndrng_Prvdr_Last_Org_Name"],axis=0)
part_b = part_b.dropna(subset=["Rndrng_Prvdr_First_Name"],axis=0)

### PRE_PROCESSING OF LEIE DATA

In [7]:
leie_ex = leie_ex.dropna(subset=["NPI"],axis=0)
ex_npi = leie_ex[leie_ex["NPI"]!=0]["NPI"]
ex_lnames = leie_ex.dropna(subset=["LASTNAME"],axis=0)["LASTNAME"]
ex_fnames = leie_ex.dropna(subset=["FIRSTNAME"],axis=0)["FIRSTNAME"]
leie_ex["MIDNAME"] = leie_ex["MIDNAME"].apply(lambda row : row if row!= " " else 0)
ex_mi = leie_ex[leie_ex["MIDNAME"]!=0]["MIDNAME"]

In [8]:
print(leie_ex.shape)
print(part_b.shape)

(76546, 18)
(1100800, 73)

In [9]:
x = part_b["Rndrng_NPI"].size
count = 0
y =[];
while (count < x):
    chk = part_b["Rndrng_NPI"].iloc[count]
    chk1 = part_b["Rndrng_Prvdr_First_Name"].iloc[count]
    chk2 = part_b["Rndrng_Prvdr_Last_Org_Name"].iloc[count]
    chk3 = part_b["Rndrng_Prvdr_MI"].iloc[count]
    if(chk in ex_npi.unique()):
        y.append(1)
    else:
        y.append(0)
    count = count+1

In [10]:
partbx = pd.DataFrame(y, columns =['Fraud'])
print(partbx.value_counts())
x=partbx.size
c=0
part_b["Fraud"]=partbx
while(c<x):
    part_b["Fraud"].iloc[c]=partbx["Fraud"].iloc[c]
    c=c+1

Fraud
0        1100684
1            116
dtype: int64

In [11]:
part_b["Fraud"].value_counts()

0.0    1100684
1.0        116
Name: Fraud, dtype: int64

In [22]:
x = part_b["Rndrng_NPI"].size
count = 0
y =[];
while (count < x):
    chk = part_b["Rndrng_NPI"].iloc[count]
    chk1 = part_b["Rndrng_Prvdr_First_Name"].iloc[count]
    chk2 = part_b["Rndrng_Prvdr_Last_Org_Name"].iloc[count]
    chk3 = part_b["Rndrng_Prvdr_MI"].iloc[count]
    if(chk in ex_npi.unique()):
        y.append(1)
    elif chk1 in ex_fnames.unique():
         y.append(1)
    elif chk2 in ex_lnames.unique():
         y.append(1)
    elif chk3 in ex_mi.unique():
         y.append(1)   
    else:
        y.append(0)
    count = count+1
    
partbx = pd.DataFrame(y, columns =['Fraud'])
print(partbx.value_counts())
x=partbx.size
c=0
part_b["Fraud"]=partbx
while(c<x):
    part_b["Fraud"].iloc[c]=partbx["Fraud"].iloc[c]
    c=c+1

Fraud
0        1099715
1           1085
dtype: int64

In [23]:
part_b["Fraud"].value_counts()

0.0    1099715
1.0       1085
Name: Fraud, dtype: int64

### ANALYSIS OF EACH COLUMN

In [24]:
part_b.columns

Index(['Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Gndr',
       'Rndrng_Prvdr_Ent_Cd', 'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2',
       'Rndrng_Prvdr_City', 'Rndrng_Prvdr_State_Abrvtn',
       'Rndrng_Prvdr_State_FIPS', 'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA',
       'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'Tot_HCPCS_Cds', 'Tot_Benes',
       'Tot_Srvcs', 'Tot_Sbmtd_Chrg', 'Tot_Mdcr_Alowd_Amt',
       'Tot_Mdcr_Pymt_Amt', 'Tot_Mdcr_Stdzd_Amt', 'Drug_Sprsn_Ind',
       'Drug_Tot_HCPCS_Cds', 'Drug_Tot_Benes', 'Drug_Tot_Srvcs',
       'Drug_Sbmtd_Chrg', 'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_CC_AF_Pct', 'Bene_CC_Alzhmr_Pct', 'Bene_CC_Asthma_Pct',
       'Bene_CC_Cncr_Pct', 'Bene_CC_CHF_Pct', 'Bene_CC_CKD_Pct',
       'Bene_CC_COPD_Pct', 'Bene_CC_Dprssn_Pct', 'Bene_CC_Dbts_Pct',
       'Bene_CC_Hyplpdma_Pct', 'Bene_CC_Hyprtnsn_Pct', 'Bene_CC_IHD_Pct',
       'Bene_CC_Opo_Pct', 'Bene_CC_RAOA_Pct', 'Bene_CC_Sz_Pct',
       'Bene_CC_Strok_Pct', 'Bene_Avg_Risk_Scre', 'Rndrng_NPI', 'Fraud'],
      dtype='object')

In [25]:
provider_data = part_b[["Rndrng_NPI","Rndrng_Prvdr_First_Name","Rndrng_Prvdr_MI","Rndrng_Prvdr_Last_Org_Name",
                    "Rndrng_Prvdr_Crdntls","Rndrng_Prvdr_Gndr","Rndrng_Prvdr_Ent_Cd",
                    "Rndrng_Prvdr_City","Rndrng_Prvdr_State_FIPS","Rndrng_Prvdr_Type",'Rndrng_Prvdr_RUCA',
                    'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry',"Rndrng_Prvdr_Mdcr_Prtcptg_Ind",
                    "Tot_HCPCS_Cds","Tot_Benes","Tot_Srvcs","Tot_Sbmtd_Chrg",
                    "Tot_Mdcr_Alowd_Amt","Tot_Mdcr_Pymt_Amt","Tot_Mdcr_Stdzd_Amt","Fraud"]]

In [26]:
bene_data = part_b[["Rndrng_NPI","Rndrng_Prvdr_First_Name","Rndrng_Prvdr_MI","Rndrng_Prvdr_Last_Org_Name",
                   "Rndrng_Prvdr_Crdntls","Rndrng_Prvdr_Gndr","Rndrng_Prvdr_Ent_Cd",
                   "Tot_Benes","Bene_Avg_Age","Bene_Age_LT_65_Cnt","Bene_Age_65_74_Cnt","Bene_Age_75_84_Cnt",
                   "Bene_Age_GT_84_Cnt","Bene_Feml_Cnt","Bene_Male_Cnt",'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
                   'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
                   'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',"Fraud"]]

In [27]:
drug_data = part_b[["Rndrng_NPI","Rndrng_Prvdr_First_Name","Rndrng_Prvdr_MI","Rndrng_Prvdr_Last_Org_Name",
                   "Rndrng_Prvdr_Crdntls","Rndrng_Prvdr_Gndr","Rndrng_Prvdr_Ent_Cd",
                   'Drug_Sprsn_Ind','Drug_Tot_HCPCS_Cds', 'Drug_Tot_Benes', 'Drug_Tot_Srvcs',
                   'Drug_Sbmtd_Chrg', 'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt','Drug_Mdcr_Stdzd_Amt',"Fraud"]]

In [28]:
medical_data = part_b[["Rndrng_NPI","Rndrng_Prvdr_First_Name","Rndrng_Prvdr_MI","Rndrng_Prvdr_Last_Org_Name",
                        "Rndrng_Prvdr_Crdntls","Rndrng_Prvdr_Gndr","Rndrng_Prvdr_Ent_Cd",'Med_Sprsn_Ind', 
                        'Med_Tot_HCPCS_Cds','Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
                        'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',"Fraud"]]

In [29]:
print(provider_data["Fraud"].value_counts())
provider_data.head(5)

0.0    1099715
1.0       1085
Name: Fraud, dtype: int64

,Rndrng_NPI,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_City,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Type,...,Rndrng_Prvdr_Cntry,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,Tot_HCPCS_Cds,Tot_Benes,Tot_Srvcs,Tot_Sbmtd_Chrg,Tot_Mdcr_Alowd_Amt,Tot_Mdcr_Pymt_Amt,Tot_Mdcr_Stdzd_Amt,Fraud
0,1003000126,Ardalan,NaN,Enkeshafi,M.D.,M,I,Bethesda,24,Internal Medicine,...,US,Y,16,291,764,"$402,812.00","$85,319.63","$69,175.78","$66,401.61",0.0
1,1003000134,Thomas,L,Cibull,M.D.,M,I,Evanston,17,Pathology,...,US,Y,18,"2,633","5,930","$915,291.00","$227,372.53","$176,497.74","$167,363.18",0.0
2,1003000142,Rashid,NaN,Khalil,M.D.,M,I,Toledo,39,Anesthesiology,...,US,Y,54,167,"2,003","$182,532.48","$101,757.15","$76,938.82","$80,179.52",0.0
3,1003000423,Jennifer,A,Velotta,M.D.,F,I,Cleveland,39,Obstetrics & Gynecology,...,US,Y,21,56,571,"$23,680.00","$9,011.99","$7,224.35","$7,301.35",0.0
4,1003000480,Kevin,B,Rothchild,MD,M,I,Aurora,08,General Surgery,...,US,Y,30,89,125,"$152,154.00","$30,631.10","$23,962.85","$23,463.98",0.0

In [30]:
print(bene_data["Fraud"].value_counts())
bene_data.head(5)

0.0    1099715
1.0       1085
Name: Fraud, dtype: int64

,Rndrng_NPI,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Tot_Benes,Bene_Avg_Age,Bene_Age_LT_65_Cnt,...,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_API_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_NatInd_Cnt,Bene_Race_Othr_Cnt,Bene_Dual_Cnt,Bene_Ndual_Cnt,Fraud
0,1003000126,Ardalan,NaN,Enkeshafi,M.D.,M,I,291,77,27,...,130,210,50,NaN,12,NaN,NaN,61,230,0.0
1,1003000134,Thomas,L,Cibull,M.D.,M,I,"2,633",76,69,...,"1,323","2,385",NaN,45,49,NaN,128,125,"2,508",0.0
2,1003000142,Rashid,NaN,Khalil,M.D.,M,I,167,65,70,...,67,115,39,0,NaN,0,NaN,59,108,0.0
3,1003000423,Jennifer,A,Velotta,M.D.,F,I,56,67,12,...,0,NaN,NaN,NaN,NaN,NaN,NaN,11,45,0.0
4,1003000480,Kevin,B,Rothchild,MD,M,I,89,64,34,...,41,68,NaN,NaN,NaN,NaN,NaN,38,51,0.0

In [31]:
print(drug_data["Fraud"].value_counts())
drug_data.head(5)

0.0    1099715
1.0       1085
Name: Fraud, dtype: int64

,Rndrng_NPI,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Drug_Sprsn_Ind,Drug_Tot_HCPCS_Cds,Drug_Tot_Benes,Drug_Tot_Srvcs,Drug_Sbmtd_Chrg,Drug_Mdcr_Alowd_Amt,Drug_Mdcr_Pymt_Amt,Drug_Mdcr_Stdzd_Amt,Fraud
0,1003000126,Ardalan,NaN,Enkeshafi,M.D.,M,I,NaN,0.0,0,0,$0.00,$0.00,$0.00,$0.00,0.0
1,1003000134,Thomas,L,Cibull,M.D.,M,I,NaN,0.0,0,0,$0.00,$0.00,$0.00,$0.00,0.0
2,1003000142,Rashid,NaN,Khalil,M.D.,M,I,*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,1003000423,Jennifer,A,Velotta,M.D.,F,I,*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,1003000480,Kevin,B,Rothchild,MD,M,I,NaN,0.0,0,0,$0.00,$0.00,$0.00,$0.00,0.0

In [32]:
print(medical_data["Fraud"].value_counts())
medical_data.head(5)

0.0    1099715
1.0       1085
Name: Fraud, dtype: int64

,Rndrng_NPI,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Gndr,Rndrng_Prvdr_Ent_Cd,Med_Sprsn_Ind,Med_Tot_HCPCS_Cds,Med_Tot_Benes,Med_Tot_Srvcs,Med_Sbmtd_Chrg,Med_Mdcr_Alowd_Amt,Med_Mdcr_Pymt_Amt,Med_Mdcr_Stdzd_Amt,Fraud
0,1003000126,Ardalan,NaN,Enkeshafi,M.D.,M,I,NaN,16.0,291,764,"$402,812.00","$85,319.63","$69,175.78","$66,401.61",0.0
1,1003000134,Thomas,L,Cibull,M.D.,M,I,NaN,18.0,"2,633","5,930","$915,291.00","$227,372.53","$176,497.74","$167,363.18",0.0
2,1003000142,Rashid,NaN,Khalil,M.D.,M,I,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,1003000423,Jennifer,A,Velotta,M.D.,F,I,#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,1003000480,Kevin,B,Rothchild,MD,M,I,NaN,30.0,89,125,"$152,154.00","$30,631.10","$23,962.85","$23,463.98",0.0

### SAVE ALL THESE AS .CSV FOR PROCESSING FURTHER

In [33]:
provider_data.to_csv('labelled_data/part_B/extra/provider_data.csv')
bene_data.to_csv('labelled_data/part_B/extra/beneficiary_data.csv')
drug_data.to_csv('labelled_data/part_B/extra/drug_data.csv')
medical_data.to_csv('labelled_data/part_B/extra/medical_data.csv')
part_b.to_csv('labelled_data/part_B/partb_data.csv')