In [95]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [96]:
df = pd.read_csv("labelled_data/part_D/partd_data.csv")

In [97]:
df

,Unnamed: 0,PRSCRBR_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_MI,Prscrbr_Crdntls,Prscrbr_Gndr,Prscrbr_Ent_Cd,Prscrbr_St1,Prscrbr_St2,...,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Dual_Cnt,Bene_Ndual_Cnt,Bene_Avg_Risk_Scre,Fraud
0,0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,M,I,6410 Rockledge Dr Ste 304,NaN,...,67.0,27.0,NaN,NaN,0.0,NaN,28.0,78.0,2.245800,0.0
1,1,1003000142,Khalil,Rashid,NaN,M.D.,M,I,4126 N Holland Sylvania Rd,Suite 220,...,130.0,81.0,NaN,12.0,0.0,NaN,125.0,103.0,1.695165,0.0
2,2,1003000167,Escobar,Julio,E,DDS,M,I,5 Pine Cone Rd,NaN,...,41.0,0.0,0.0,NaN,0.0,NaN,0.0,43.0,1.006070,0.0
3,3,1003000175,Reyes-Vasquez,Belinda,NaN,D.D.S.,F,I,322 N Azusa Ave Ste 202,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.251869,0.0
4,4,1003000282,Blakemore,Rosie,K,FNP,F,I,Tennessee Prison For Women,3881 Stewarts Lane,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.919074,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255119,1255170,1992999569,Yuen,Jenny,F,"O.D., F.A.A.O",F,I,515 Gough St,NaN,...,NaN,0.0,16.0,0.0,0.0,NaN,NaN,NaN,1.451353,0.0
1255120,1255171,1992999650,Yong,Wayne,B,DMD,M,I,28 Atlantic Avenue,121,...,NaN,NaN,18.0,0.0,0.0,NaN,NaN,NaN,1.344691,0.0
1255121,1255172,1992999759,Soriano,Dino,V,RN MSN HSA FNP-C,M,I,171 Clover Point Cir,NaN,...,16.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN,1.545349,1.0
1255122,1255173,1992999825,Deschenes,Geoffrey,R,M.D.,M,I,1100 9th Ave,Ms:m4-Pfs,...,100.0,NaN,16.0,NaN,0.0,NaN,18.0,108.0,1.109445,0.0
1255123,1255174,1992999874,Joffe,Gabriella,NaN,NaN,F,I,5620 Brook Rd,NaN,...,74.0,25.0,NaN,NaN,0.0,NaN,28.0,75.0,2.748669,0.0

In [98]:
df.columns

Index(['Unnamed: 0', 'PRSCRBR_NPI', 'Prscrbr_Last_Org_Name',
       'Prscrbr_First_Name', 'Prscrbr_MI', 'Prscrbr_Crdntls', 'Prscrbr_Gndr',
       'Prscrbr_Ent_Cd', 'Prscrbr_St1', 'Prscrbr_St2', 'Prscrbr_City',
       'Prscrbr_State_Abrvtn', 'Prscrbr_State_FIPS', 'Prscrbr_zip5',
       'Prscrbr_RUCA', 'Prscrbr_RUCA_Desc', 'Prscrbr_Cntry', 'Prscrbr_Type',
       'Prscrbr_Type_src', 'Tot_Clms', 'Tot_30day_Fills', 'Tot_Drug_Cst',
       'Tot_Day_Suply', 'Tot_Benes', 'GE65_Sprsn_Flag', 'GE65_Tot_Clms',
       'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst', 'GE65_Tot_Day_Suply',
       'GE65_Bene_Sprsn_Flag', 'GE65_Tot_Benes', 'Brnd_Sprsn_Flag',
       'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst', 'Gnrc_Sprsn_Flag',
       'Gnrc_Tot_Clms', 'Gnrc_Tot_Drug_Cst', 'Othr_Sprsn_Flag',
       'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst', 'MAPD_Sprsn_Flag',
       'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst', 'PDP_Sprsn_Flag', 'PDP_Tot_Clms',
       'PDP_Tot_Drug_Cst', 'LIS_Sprsn_Flag', 'LIS_Tot_Clms', 'LIS_Drug_Cst',
       'NonLIS_Sprsn_Flag', 'NonLIS_Tot_Clms', 'NonLIS_Drug_Cst',
       'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
       'Opioid_Tot_Benes', 'Opioid_Prscrbr_Rate', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply', 'Opioid_LA_Tot_Benes',
       'Opioid_LA_Prscrbr_Rate', 'Antbtc_Tot_Clms', 'Antbtc_Tot_Drug_Cst',
       'Antbtc_Tot_Benes', 'Antpsyct_GE65_Sprsn_Flag',
       'Antpsyct_GE65_Tot_Clms', 'Antpsyct_GE65_Tot_Drug_Cst',
       'Antpsyct_GE65_Bene_Suprsn_Flag', 'Antpsyct_GE65_Tot_Benes',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_Api_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_Natind_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_Avg_Risk_Scre', 'Fraud'],
      dtype='object')

In [99]:
df["GE65_Tot_Drug_Cst"]

0          17117.40
1          18262.43
2               NaN
3               NaN
4               NaN
             ...
1255119         NaN
1255120         NaN
1255121     4832.38
1255122    10090.12
1255123    11725.70
Name: GE65_Tot_Drug_Cst, Length: 1255124, dtype: float64

In [100]:
df = df[['PRSCRBR_NPI','Prscrbr_Type','Tot_Clms', 'Tot_30day_Fills', 'Tot_Drug_Cst','Tot_Day_Suply', 'Tot_Benes', 'GE65_Tot_Clms','GE65_Tot_30day_Fills', 
    'GE65_Tot_Drug_Cst', 'GE65_Tot_Day_Suply', 'GE65_Tot_Benes', 'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst', 'Gnrc_Tot_Clms', 
    'Gnrc_Tot_Drug_Cst','Othr_Tot_Clms','Othr_Tot_Drug_Cst', 'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst', 'PDP_Tot_Clms','PDP_Tot_Drug_Cst', 
    'LIS_Tot_Clms', 'LIS_Drug_Cst','NonLIS_Tot_Clms','NonLIS_Drug_Cst','Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst', 'Opioid_Tot_Suply',
    'Opioid_Tot_Benes', 'Opioid_LA_Tot_Clms','Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply', 'Opioid_LA_Tot_Benes','Antbtc_Tot_Clms', 
    'Antbtc_Tot_Drug_Cst','Antbtc_Tot_Benes', 'Antpsyct_GE65_Tot_Clms', 'Antpsyct_GE65_Tot_Drug_Cst','Antpsyct_GE65_Tot_Benes','Fraud']]

In [101]:
df

,PRSCRBR_NPI,Prscrbr_Type,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
0,1003000126,Internal Medicine,324,369.800000,20606.08,8621,106.0,277.0,308.233333,17117.40,...,0.00,0.0,NaN,42.0,4868.85,38.0,0.0,0.0,0.0,0.0
1,1003000142,Anesthesiology,1992,2145.666667,79803.65,60953,228.0,727.0,805.066667,18262.43,...,23115.25,4464.0,22.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,1003000167,Dentist,57,57.700000,327.34,554,43.0,NaN,NaN,NaN,...,NaN,NaN,NaN,46.0,262.79,40.0,NaN,NaN,NaN,0.0
3,1003000175,Dentist,18,18.000000,128.52,181,NaN,NaN,NaN,NaN,...,0.00,0.0,NaN,16.0,116.30,NaN,NaN,NaN,NaN,0.0
4,1003000282,Nurse Practitioner,37,47.000000,3834.98,1366,NaN,NaN,NaN,NaN,...,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255119,1992999569,Optometry,40,80.666667,9870.01,2357,17.0,NaN,NaN,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,NaN,NaN,NaN,0.0
1255120,1992999650,Dentist,72,73.200000,397.84,1092,27.0,NaN,NaN,NaN,...,0.00,0.0,0.0,27.0,113.92,18.0,NaN,NaN,NaN,0.0
1255121,1992999759,Nurse Practitioner,47,90.466667,13618.96,2704,21.0,17.0,34.000000,4832.38,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,NaN,1.0
1255122,1992999825,Otolaryngology,249,291.066667,10899.52,5801,126.0,217.0,255.066667,10090.12,...,0.00,0.0,0.0,64.0,1233.49,53.0,0.0,0.0,0.0,0.0
1255123,1992999874,Internal Medicine,274,290.633333,14449.86,6436,103.0,242.0,257.500000,11725.70,...,0.00,0.0,0.0,39.0,530.62,31.0,0.0,0.0,0.0,0.0

In [102]:
df.dtypes

PRSCRBR_NPI                     int64
Prscrbr_Type                   object
Tot_Clms                        int64
Tot_30day_Fills               float64
Tot_Drug_Cst                  float64
Tot_Day_Suply                   int64
Tot_Benes                     float64
GE65_Tot_Clms                 float64
GE65_Tot_30day_Fills          float64
GE65_Tot_Drug_Cst             float64
GE65_Tot_Day_Suply            float64
GE65_Tot_Benes                float64
Brnd_Tot_Clms                 float64
Brnd_Tot_Drug_Cst             float64
Gnrc_Tot_Clms                 float64
Gnrc_Tot_Drug_Cst             float64
Othr_Tot_Clms                 float64
Othr_Tot_Drug_Cst             float64
MAPD_Tot_Clms                 float64
MAPD_Tot_Drug_Cst             float64
PDP_Tot_Clms                  float64
PDP_Tot_Drug_Cst              float64
LIS_Tot_Clms                  float64
LIS_Drug_Cst                  float64
NonLIS_Tot_Clms               float64
NonLIS_Drug_Cst               float64
Opioid_Tot_Clms               float64
Opioid_Tot_Drug_Cst           float64
Opioid_Tot_Suply              float64
Opioid_Tot_Benes              float64
Opioid_LA_Tot_Clms            float64
Opioid_LA_Tot_Drug_Cst        float64
Opioid_LA_Tot_Suply           float64
Opioid_LA_Tot_Benes           float64
Antbtc_Tot_Clms               float64
Antbtc_Tot_Drug_Cst           float64
Antbtc_Tot_Benes              float64
Antpsyct_GE65_Tot_Clms        float64
Antpsyct_GE65_Tot_Drug_Cst    float64
Antpsyct_GE65_Tot_Benes       float64
Fraud                         float64
dtype: object

In [103]:
print(df["Tot_Clms"].isnull().sum())
print(df["Tot_30day_Fills"].isnull().sum())
print(df["Tot_Drug_Cst"].isnull().sum())
print(df["Tot_Day_Suply"].isnull().sum())
print("-------------------------------------------------")
print(df["Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["GE65_Tot_Clms"].isnull().sum())
print(df["GE65_Tot_30day_Fills"].isnull().sum())
print(df["GE65_Tot_Drug_Cst"].isnull().sum())
print(df["GE65_Tot_Day_Suply"].isnull().sum())
print(df["GE65_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Brnd_Tot_Clms"].isnull().sum())
print(df["Brnd_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Gnrc_Tot_Clms"].isnull().sum())
print(df["Gnrc_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Othr_Tot_Clms"].isnull().sum())
print(df["Othr_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["MAPD_Tot_Clms"].isnull().sum())
print(df["MAPD_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["PDP_Tot_Clms"].isnull().sum())
print(df["PDP_Tot_Drug_Cst"].isnull().sum())
print(df["LIS_Tot_Clms"].isnull().sum())
print(df["LIS_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_Tot_Clms"].isnull().sum())
print(df["Opioid_Tot_Drug_Cst"].isnull().sum())
print(df["Opioid_Tot_Suply"].isnull().sum())
print(df["Opioid_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_LA_Tot_Clms"].isnull().sum())
print(df["Opioid_LA_Tot_Drug_Cst"].isnull().sum())
print(df["Opioid_LA_Tot_Suply"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Antbtc_Tot_Clms"].isnull().sum())
print(df["Antbtc_Tot_Drug_Cst"].isnull().sum())
print(df["Antbtc_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Antpsyct_GE65_Tot_Clms"].isnull().sum())
print(df["Antpsyct_GE65_Tot_Drug_Cst"].isnull().sum())
print(df["Antpsyct_GE65_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())

0
0
0
0
-------------------------------------------------
142956
-------------------------------------------------
294227
294227
294227
294227
592000
-------------------------------------------------
543484
543484
-------------------------------------------------
30172
30172
-------------------------------------------------
538251
538251
-------------------------------------------------
231297
231297
-------------------------------------------------
231297
231297
266730
266730
-------------------------------------------------
347133
347133
347133
523631
-------------------------------------------------
432770
432770
432770
651650
-------------------------------------------------
373592
373592
501293
-------------------------------------------------
459981
459981
797381
-------------------------------------------------
651650
651650
651650
651650

## Finding where all the major columns are NULL

In [104]:
x = len(df)
y = len(df.columns)
all_nan1 = []
for i in range(x):
    if df.iloc[i].isnull().sum()>=34:
        all_nan1.append(i)

In [105]:
len(all_nan1)

121

## Dropping all 121 records from the dataframe and all those records are non-fraud

In [106]:
all_nan_df = []
for i in all_nan1:
    df = df.drop(i,axis=0)
    all_nan_df.append(df.iloc[i])

In [107]:
 pd.DataFrame(all_nan_df)

,PRSCRBR_NPI,Prscrbr_Type,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
8473,1003840505,Obstetrics & Gynecology,107,158.766667,1536.94,4722,15.0,94.0,145.766667,1498.90,...,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,NaN,0.0
33755,1023397544,Dentist,75,92.000000,412.53,1102,42.0,NaN,NaN,NaN,...,0.0,0.0,NaN,35.0,148.43,30.0,NaN,NaN,NaN,0.0
40698,1033188453,Dentist,65,65.000000,294.42,540,46.0,NaN,NaN,NaN,...,0.0,0.0,0.0,65.0,294.42,46.0,NaN,NaN,NaN,0.0
54403,1043326911,Psychiatry,1488,1603.800000,222316.39,47880,48.0,624.0,726.400000,51801.06,...,0.0,0.0,0.0,NaN,NaN,NaN,146.0,42219.57,14.0,0.0
73843,1053852566,Student in an Organized Health Care Education/...,109,109.000000,793.29,668,51.0,91.0,91.000000,668.74,...,0.0,0.0,0.0,46.0,485.97,44.0,0.0,0.00,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199409,1952601312,Podiatry,239,276.333333,3611.69,6320,92.0,174.0,190.666667,2465.37,...,0.0,0.0,0.0,23.0,400.35,13.0,0.0,0.00,0.0,0.0
1212370,1962672584,Family Practice,3281,7832.866667,220933.79,230707,348.0,2944.0,7143.966667,192436.44,...,0.0,0.0,0.0,56.0,1392.91,45.0,11.0,386.12,NaN,0.0
1232399,1982149878,Nurse Practitioner,127,129.000000,4264.12,1633,91.0,98.0,98.000000,3645.38,...,NaN,NaN,NaN,56.0,502.84,53.0,0.0,0.00,0.0,0.0
1245075,1992157606,Nurse Practitioner,3645,8509.766667,286874.34,248686,366.0,3276.0,7735.566667,276068.49,...,0.0,0.0,0.0,90.0,968.41,56.0,NaN,NaN,NaN,0.0
1246827,1992268452,Student in an Organized Health Care Education/...,439,841.500000,35639.09,23816,72.0,412.0,806.333333,31851.02,...,0.0,0.0,0.0,26.0,387.34,21.0,NaN,NaN,NaN,0.0

In [108]:
all_nan_df = pd.DataFrame(all_nan_df)

In [109]:
all_nan_df.iloc[2].isnull().sum()

12

In [110]:
all_nan_df["Fraud"].value_counts()

0.0    121
Name: Fraud, dtype: int64

In [111]:
df

,PRSCRBR_NPI,Prscrbr_Type,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
0,1003000126,Internal Medicine,324,369.800000,20606.08,8621,106.0,277.0,308.233333,17117.40,...,0.00,0.0,NaN,42.0,4868.85,38.0,0.0,0.0,0.0,0.0
1,1003000142,Anesthesiology,1992,2145.666667,79803.65,60953,228.0,727.0,805.066667,18262.43,...,23115.25,4464.0,22.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,1003000167,Dentist,57,57.700000,327.34,554,43.0,NaN,NaN,NaN,...,NaN,NaN,NaN,46.0,262.79,40.0,NaN,NaN,NaN,0.0
3,1003000175,Dentist,18,18.000000,128.52,181,NaN,NaN,NaN,NaN,...,0.00,0.0,NaN,16.0,116.30,NaN,NaN,NaN,NaN,0.0
4,1003000282,Nurse Practitioner,37,47.000000,3834.98,1366,NaN,NaN,NaN,NaN,...,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255119,1992999569,Optometry,40,80.666667,9870.01,2357,17.0,NaN,NaN,NaN,...,0.00,0.0,0.0,0.0,0.00,0.0,NaN,NaN,NaN,0.0
1255120,1992999650,Dentist,72,73.200000,397.84,1092,27.0,NaN,NaN,NaN,...,0.00,0.0,0.0,27.0,113.92,18.0,NaN,NaN,NaN,0.0
1255121,1992999759,Nurse Practitioner,47,90.466667,13618.96,2704,21.0,17.0,34.000000,4832.38,...,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,NaN,1.0
1255122,1992999825,Otolaryngology,249,291.066667,10899.52,5801,126.0,217.0,255.066667,10090.12,...,0.00,0.0,0.0,64.0,1233.49,53.0,0.0,0.0,0.0,0.0
1255123,1992999874,Internal Medicine,274,290.633333,14449.86,6436,103.0,242.0,257.500000,11725.70,...,0.00,0.0,0.0,39.0,530.62,31.0,0.0,0.0,0.0,0.0

In [112]:
print(df["Tot_Clms"].isnull().sum())
print(df["Tot_30day_Fills"].isnull().sum())
print(df["Tot_Drug_Cst"].isnull().sum())
print(df["Tot_Day_Suply"].isnull().sum())
print("-------------------------------------------------")
print(df["Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["GE65_Tot_Clms"].isnull().sum())
print(df["GE65_Tot_30day_Fills"].isnull().sum())
print(df["GE65_Tot_Drug_Cst"].isnull().sum())
print(df["GE65_Tot_Day_Suply"].isnull().sum())
print(df["GE65_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Brnd_Tot_Clms"].isnull().sum())
print(df["Brnd_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Gnrc_Tot_Clms"].isnull().sum())
print(df["Gnrc_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Othr_Tot_Clms"].isnull().sum())
print(df["Othr_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["MAPD_Tot_Clms"].isnull().sum())
print(df["MAPD_Tot_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["PDP_Tot_Clms"].isnull().sum())
print(df["PDP_Tot_Drug_Cst"].isnull().sum())
print(df["LIS_Tot_Clms"].isnull().sum())
print(df["LIS_Drug_Cst"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_Tot_Clms"].isnull().sum())
print(df["Opioid_Tot_Drug_Cst"].isnull().sum())
print(df["Opioid_Tot_Suply"].isnull().sum())
print(df["Opioid_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_LA_Tot_Clms"].isnull().sum())
print(df["Opioid_LA_Tot_Drug_Cst"].isnull().sum())
print(df["Opioid_LA_Tot_Suply"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Antbtc_Tot_Clms"].isnull().sum())
print(df["Antbtc_Tot_Drug_Cst"].isnull().sum())
print(df["Antbtc_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Antpsyct_GE65_Tot_Clms"].isnull().sum())
print(df["Antpsyct_GE65_Tot_Drug_Cst"].isnull().sum())
print(df["Antpsyct_GE65_Tot_Benes"].isnull().sum())
print("-------------------------------------------------")
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())
print(df["Opioid_LA_Tot_Benes"].isnull().sum())

0
0
0
0
-------------------------------------------------
142835
-------------------------------------------------
294106
294106
294106
294106
591879
-------------------------------------------------
543363
543363
-------------------------------------------------
30051
30051
-------------------------------------------------
538130
538130
-------------------------------------------------
231176
231176
-------------------------------------------------
231176
231176
266609
266609
-------------------------------------------------
347012
347012
347012
523510
-------------------------------------------------
432649
432649
432649
651529
-------------------------------------------------
373471
373471
501172
-------------------------------------------------
459860
459860
797260
-------------------------------------------------
651529
651529
651529
651529

## Now, we divide accordingly

## First GDRC coz we have less

In [113]:
print(df["Gnrc_Tot_Clms"].isnull().sum())
print(df["Gnrc_Tot_Drug_Cst"].isnull().sum())

30051
30051

In [118]:
gnrc_nan = []
no_gnrc = []
for i in range(len(df)):
    if(pd.isnull(df.iloc[i].Gnrc_Tot_Clms) == True and pd.isnull(df.iloc[i].Gnrc_Tot_Drug_Cst)):
        gnrc_nan.append(df.iloc[i])
    else:
        no_gnrc.append(df.iloc[i])

In [119]:
gnrc_nan = pd.DataFrame(gnrc_nan)
no_gnrc = pd.DataFrame(no_gnrc)

In [120]:
print(len(gnrc_nan))
gnrc_nan["Fraud"].value_counts()

30051

0.0    30001
1.0       50
Name: Fraud, dtype: int64

In [62]:
df.drop("Prscrbr_Type",axis=1).corr()

,PRSCRBR_NPI,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
PRSCRBR_NPI,1.000000,-0.000505,-0.000354,0.000972,-0.000343,0.001489,-0.000481,-0.000356,0.001504,-0.000353,...,-0.001128,-0.001109,-0.001050,-0.001270,0.000135,-0.001314,-0.000835,-0.000176,0.001056,-0.000349
Tot_Clms,-0.000505,1.000000,0.953939,0.543884,0.919410,0.501186,0.980677,0.923330,0.537388,0.886105,...,0.160435,0.208818,0.193927,0.645953,0.154193,0.550095,0.546575,0.243171,0.594437,0.005485
Tot_30day_Fills,-0.000354,0.953939,1.000000,0.521138,0.991127,0.476152,0.951925,0.989000,0.528775,0.978563,...,0.117490,0.156394,0.126815,0.619078,0.126023,0.555469,0.398686,0.169774,0.486101,0.005303
Tot_Drug_Cst,0.000972,0.543884,0.521138,1.000000,0.508296,0.373992,0.502474,0.476178,0.943861,0.461423,...,0.105978,0.121170,0.114902,0.335499,0.192723,0.258902,0.250240,0.215825,0.268330,0.002814
Tot_Day_Suply,-0.000343,0.919410,0.991127,0.508296,1.000000,0.407318,0.914968,0.980719,0.513159,0.989076,...,0.116134,0.153680,0.122048,0.596029,0.114624,0.541616,0.344687,0.154459,0.451857,0.005189
Tot_Benes,0.001489,0.501186,0.476152,0.373992,0.407318,1.000000,0.499381,0.460563,0.397717,0.384599,...,0.103209,0.136292,0.161214,0.284966,0.062034,0.296099,0.167091,0.079316,0.227059,0.003204
GE65_Tot_Clms,-0.000481,0.980677,0.951925,0.502474,0.914968,0.499381,1.000000,0.951742,0.548354,0.913383,...,0.105431,0.146279,0.125488,0.636820,0.138592,0.549454,0.489162,0.187980,0.533988,0.007063
GE65_Tot_30day_Fills,-0.000356,0.923330,0.989000,0.476178,0.980719,0.460563,0.951742,1.000000,0.528051,0.990446,...,0.076087,0.108678,0.074641,0.598715,0.108121,0.544935,0.349235,0.128154,0.429935,0.006877
GE65_Tot_Drug_Cst,0.001504,0.537388,0.528775,0.943861,0.513159,0.397717,0.548354,0.528051,1.000000,0.510923,...,0.068530,0.086444,0.080088,0.330083,0.152052,0.265880,0.205519,0.154632,0.225266,0.003844
GE65_Tot_Day_Suply,-0.000353,0.886105,0.978563,0.461423,0.989076,0.384599,0.913383,0.990446,0.510923,1.000000,...,0.074412,0.105461,0.069374,0.575124,0.096837,0.530818,0.295660,0.113168,0.394002,0.006726
GE65_Tot_Benes,0.001826,0.445367,0.423123,0.329235,0.347152,0.996393,0.475642,0.437134,0.391247,0.356404,...,0.047462,0.069730,0.078352,0.237676,0.041794,0.250400,0.118110,0.041378,0.182833,0.004211
Brnd_Tot_Clms,0.000153,0.749965,0.668105,0.578801,0.592664,0.841318,0.749027,0.647391,0.606895,0.565302,...,0.086132,0.106432,0.084905,0.449881,0.120849,0.385243,0.383863,0.173686,0.419648,0.003385
Brnd_Tot_Drug_Cst,-0.000071,0.460074,0.436305,0.991648,0.420813,0.352298,0.420613,0.392250,0.931175,0.374328,...,0.067740,0.074853,0.063512,0.295899,0.174345,0.241099,0.189120,0.179976,0.203864,0.002075
Gnrc_Tot_Clms,-0.000610,0.990029,0.951069,0.499367,0.926454,0.467253,0.965884,0.918043,0.484348,0.891852,...,0.167221,0.219414,0.206819,0.652974,0.149243,0.560267,0.562840,0.273569,0.613309,0.005923
Gnrc_Tot_Drug_Cst,0.000711,0.838130,0.808338,0.659470,0.795998,0.429624,0.798823,0.765936,0.616029,0.752615,...,0.227606,0.264206,0.258182,0.569944,0.222797,0.468765,0.491802,0.322271,0.541932,0.008674
Othr_Tot_Clms,-0.000024,0.582099,0.580497,0.444777,0.582043,0.245411,0.560999,0.548814,0.440903,0.549596,...,0.020962,0.033563,0.006035,0.392240,0.070757,0.366707,0.185670,0.063161,0.209619,0.001048
Othr_Tot_Drug_Cst,0.000492,0.330697,0.346228,0.350206,0.349349,0.159567,0.309880,0.319848,0.338391,0.322328,...,0.010856,0.016552,-0.000371,0.236568,0.045353,0.218845,0.091170,0.029552,0.091385,0.000986
MAPD_Tot_Clms,-0.000359,0.860633,0.847388,0.442896,0.826368,0.441399,0.833079,0.812271,0.436205,0.789072,...,0.138046,0.184726,0.172666,0.539068,0.112788,0.483910,0.410957,0.162705,0.492473,0.003770
MAPD_Tot_Drug_Cst,0.001206,0.490356,0.482162,0.865585,0.473228,0.345165,0.452464,0.441347,0.799861,0.430537,...,0.088612,0.103966,0.100461,0.298567,0.188722,0.244656,0.186907,0.148603,0.216304,0.001563
PDP_Tot_Clms,-0.000556,0.893502,0.826612,0.490631,0.785895,0.420915,0.879397,0.801761,0.493246,0.759538,...,0.135798,0.173591,0.162336,0.575241,0.145114,0.465947,0.535277,0.252583,0.547930,0.006760
PDP_Tot_Drug_Cst,0.001037,0.468142,0.436699,0.920076,0.422533,0.312219,0.437971,0.403807,0.877580,0.388262,...,0.091368,0.101652,0.098123,0.278197,0.152487,0.200671,0.245111,0.223539,0.254216,0.003834
LIS_Tot_Clms,-0.000853,0.836644,0.690180,0.433504,0.635935,0.258476,0.784888,0.631556,0.402615,0.576984,...,0.136534,0.176978,0.174640,0.523453,0.158582,0.398254,0.634572,0.301648,0.607266,0.002645
LIS_Drug_Cst,-0.000035,0.526001,0.449540,0.835124,0.434913,0.216813,0.462593,0.388224,0.690982,0.372833,...,0.106526,0.115239,0.111075,0.322329,0.221343,0.229231,0.345168,0.281593,0.357348,0.001972
NonLIS_Tot_Clms,0.000059,0.826059,0.895775,0.444840,0.890791,0.554806,0.841254,0.901567,0.479251,0.894167,...,0.118827,0.157196,0.132249,0.535445,0.081667,0.502609,0.254338,0.089001,0.350228,0.008318
NonLIS_Drug_Cst,0.001732,0.381800,0.411790,0.868110,0.403320,0.386056,0.384915,0.408480,0.903567,0.398083,...,0.063382,0.077623,0.072297,0.222243,0.099551,0.181306,0.073537,0.081812,0.090557,0.003672
Opioid_Tot_Clms,-0.000583,0.400203,0.343261,0.192777,0.335224,0.179878,0.327296,0.282989,0.153328,0.274540,...,0.692388,0.842932,0.784755,0.293842,0.060869,0.252150,0.130793,0.041369,0.126778,0.003888
Opioid_Tot_Drug_Cst,-0.000951,0.211051,0.163609,0.123559,0.161132,0.100260,0.149603,0.116575,0.083593,0.113763,...,0.956720,0.909261,0.820343,0.101890,0.023574,0.075503,0.049542,0.015511,0.043594,0.003333
Opioid_Tot_Suply,-0.000724,0.356633,0.306611,0.177127,0.303731,0.163899,0.283798,0.248145,0.137210,0.244648,...,0.705303,0.857936,0.792257,0.231555,0.047465,0.193157,0.097424,0.030474,0.095324,0.003544
Opioid_Tot_Benes,-0.000053,0.376591,0.329226,0.170855,0.318443,0.218752,0.313891,0.273290,0.135894,0.262174,...,0.519493,0.649603,0.734394,0.365922,0.054443,0.380442,0.108859,0.027425,0.109147,0.005184
Opioid_LA_Tot_Clms,-0.001067,0.220197,0.163589,0.124443,0.158701,0.138494,0.157810,0.115545,0.089855,0.110240,...,0.874110,0.997017,0.900781,0.088426,0.024094,0.056418,0.061287,0.019612,0.053978,0.002148
Opioid_LA_Tot_Drug_Cst,-0.001128,0.160435,0.117490,0.105978,0.116134,0.103209,0.105431,0.076087,0.068530,0.074412,...,1.000000,0.876810,0.791756,0.052221,0.012430,0.031289,0.027344,0.007631,0.021483,0.002715
Opioid_LA_Tot_Suply,-0.001109,0.208818,0.156394,0.121170,0.153680,0.136292,0.146279,0.108678,0.086444,0.105461,...,0.876810,1.000000,0.900384,0.077038,0.018759,0.049501,0.046224,0.013775,0.039342,0.002161
Opioid_LA_Tot_Benes,-0.001050,0.193927,0.126815,0.114902,0.122048,0.161214,0.125488,0.074641,0.080088,0.069374,...,0.791756,0.900384,1.000000,0.034745,0.010827,0.012325,0.036837,0.011092,0.033071,0.001481
Antbtc_Tot_Clms,-0.001270,0.645953,0.619078,0.335499,0.596029,0.284966,0.636820,0.598715,0.330083,0.575124,...,0.052221,0.077038,0.034745,1.000000,0.291647,0.921878,0.312669,0.114014,0.351897,0.006786
Antbtc_Tot_Drug_Cst,0.000135,0.154193,0.126023,0.192723,0.114624,0.062034,0.138592,0.108121,0.152052,0.096837,...,0.012430,0.018759,0.010827,0.291647,1.000000,0.164416,0.108550,0.050597,0.104895,0.000819
Antbtc_Tot_Benes,-0.001314,0.550095,0.555469,0.258902,0.541616,0.296099,0.549454,0.544935,0.265880,0.530818,...,0.031289,0.049501,0.012325,0.921878,0.164416,1.000000,0.198845,0.044013,0.239327,0.006991
Antpsyct_GE65_Tot_Clms,-0.000835,0.546575,0.398686,0.250240,0.344687,0.167091,0.489162,0.349235,0.205519,0.295660,...,0.027344,0.046224,0.036837,0.312669,0.108550,0.198845,1.000000,0.588492,0.906148,0.003792
Antpsyct_GE65_Tot_Drug_Cst,-0.000176,0.243171,0.169774,0.215825,0.154459,0.079316,0.187980,0.128154,0.154632,0.113168,...,0.007631,0.013775,0.011092,0.114014,0.050597,0.044013,0.588492,1.000000,0.553995,0.001242
Antpsyct_GE65_Tot_Benes,0.001056,0.594437,0.486101,0.268330,0.451857,0.227059,0.533988,0.429935,0.225266,0.394002,...,0.021483,0.039342,0.033071,0.351897,0.104895,0.239327,0.906148,0.553995,1.000000,0.004802
Fraud,-0.000349,0.005485,0.005303,0.002814,0.005189,0.003204,0.007063,0.006877,0.003844,0.006726,...,0.002715,0.002161,0.001481,0.006786,0.000819,0.006991,0.003792,0.001242,0.004802,1.000000

In [121]:
gnrc_nan

,PRSCRBR_NPI,Prscrbr_Type,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
55,1003004128,Internal Medicine,43,59.933333,15649.20,1766,NaN,24.0,26.266667,8897.99,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
72,1003005745,Neurology,23,25.000000,1038222.89,672,NaN,0.0,0.000000,0.00,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
181,1003012022,Pulmonary Disease,169,204.766667,47070.16,5232,55.0,101.0,113.000000,28566.33,...,0.0,0.0,0.0,27.0,3176.55,19.0,0.0,0.0,0.0,0.0
217,1003013301,Dentist,11,13.600000,111.85,224,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
273,1003015553,Diagnostic Radiology,12,12.000000,157.81,343,NaN,12.0,12.000000,157.81,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254827,1992979322,Physician Assistant,11,11.000000,2381.37,210,NaN,11.0,11.000000,2381.37,...,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
1254956,1992989271,Dentist,15,15.000000,423.66,226,11.0,15.0,15.000000,423.66,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1254973,1992990360,Optometry,12,28.666667,318.80,832,NaN,12.0,28.666667,318.80,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
1254995,1992991335,Specialist,12,24.900000,10649.70,747,NaN,0.0,0.000000,0.00,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
1255092,1992997969,Optometry,19,27.000000,5884.66,746,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,0.00,NaN,NaN,NaN,NaN,0.0

In [123]:
print(len(no_gnrc))
no_gnrc["Fraud"].value_counts()

1224952

0.0    1223508
1.0       1444
Name: Fraud, dtype: int64

In [126]:
gnrc_nan.drop(["Gnrc_Tot_Clms","Gnrc_Tot_Drug_Cst"],axis=1)

,PRSCRBR_NPI,Prscrbr_Type,Tot_Clms,Tot_30day_Fills,Tot_Drug_Cst,Tot_Day_Suply,Tot_Benes,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,...,Opioid_LA_Tot_Drug_Cst,Opioid_LA_Tot_Suply,Opioid_LA_Tot_Benes,Antbtc_Tot_Clms,Antbtc_Tot_Drug_Cst,Antbtc_Tot_Benes,Antpsyct_GE65_Tot_Clms,Antpsyct_GE65_Tot_Drug_Cst,Antpsyct_GE65_Tot_Benes,Fraud
55,1003004128,Internal Medicine,43,59.933333,15649.20,1766,NaN,24.0,26.266667,8897.99,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
72,1003005745,Neurology,23,25.000000,1038222.89,672,NaN,0.0,0.000000,0.00,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
181,1003012022,Pulmonary Disease,169,204.766667,47070.16,5232,55.0,101.0,113.000000,28566.33,...,0.0,0.0,0.0,27.0,3176.55,19.0,0.0,0.0,0.0,0.0
217,1003013301,Dentist,11,13.600000,111.85,224,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
273,1003015553,Diagnostic Radiology,12,12.000000,157.81,343,NaN,12.0,12.000000,157.81,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254827,1992979322,Physician Assistant,11,11.000000,2381.37,210,NaN,11.0,11.000000,2381.37,...,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
1254956,1992989271,Dentist,15,15.000000,423.66,226,11.0,15.0,15.000000,423.66,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1254973,1992990360,Optometry,12,28.666667,318.80,832,NaN,12.0,28.666667,318.80,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
1254995,1992991335,Specialist,12,24.900000,10649.70,747,NaN,0.0,0.000000,0.00,...,0.0,0.0,NaN,0.0,0.00,NaN,0.0,0.0,NaN,0.0
1255092,1992997969,Optometry,19,27.000000,5884.66,746,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,0.00,NaN,NaN,NaN,NaN,0.0

In [127]:
gnrc_nan.columns

Index(['PRSCRBR_NPI', 'Prscrbr_Type', 'Tot_Clms', 'Tot_30day_Fills',
       'Tot_Drug_Cst', 'Tot_Day_Suply', 'Tot_Benes', 'GE65_Tot_Clms',
       'GE65_Tot_30day_Fills', 'GE65_Tot_Drug_Cst', 'GE65_Tot_Day_Suply',
       'GE65_Tot_Benes', 'Brnd_Tot_Clms', 'Brnd_Tot_Drug_Cst', 'Gnrc_Tot_Clms',
       'Gnrc_Tot_Drug_Cst', 'Othr_Tot_Clms', 'Othr_Tot_Drug_Cst',
       'MAPD_Tot_Clms', 'MAPD_Tot_Drug_Cst', 'PDP_Tot_Clms',
       'PDP_Tot_Drug_Cst', 'LIS_Tot_Clms', 'LIS_Drug_Cst', 'NonLIS_Tot_Clms',
       'NonLIS_Drug_Cst', 'Opioid_Tot_Clms', 'Opioid_Tot_Drug_Cst',
       'Opioid_Tot_Suply', 'Opioid_Tot_Benes', 'Opioid_LA_Tot_Clms',
       'Opioid_LA_Tot_Drug_Cst', 'Opioid_LA_Tot_Suply', 'Opioid_LA_Tot_Benes',
       'Antbtc_Tot_Clms', 'Antbtc_Tot_Drug_Cst', 'Antbtc_Tot_Benes',
       'Antpsyct_GE65_Tot_Clms', 'Antpsyct_GE65_Tot_Drug_Cst',
       'Antpsyct_GE65_Tot_Benes', 'Fraud'],
      dtype='object')

In [149]:
gnrc_nan["Opioid_LA_Tot_Benes"].value_counts()

0.0    6666
Name: Opioid_LA_Tot_Benes, dtype: int64

In [150]:
gnrc_nan = gnrc_nan.drop(["Gnrc_Tot_Clms","Gnrc_Tot_Drug_Cst"],axis=1)

In [152]:
gnrc_nan.to_csv("labelled_data/part_D/no_gnrc.csv")

In [26]:
fraud_tot_ben = []
nf_tot_ben = []
for i in range(len(df)):
    if(pd.isnull(df.iloc[i].Tot_Benes)== True):
        if(df.iloc[i].Fraud == 1):
            fraud_tot_ben.append(i)
        else:
            nf_tot_ben.append(i)

In [28]:
len(fraud_tot_ben)

243

In [29]:
len(nf_tot_ben)

142592

In [31]:
fraud_tot = []
nf_tot = []
for i in range(len(df)):
    if pd.isnull(df.iloc[i].Tot_Clms)== True and pd.isnull(df.iloc[i].Tot_30day_Fills)== True and pd.isnull(df.iloc[i].Tot_Drug_Cst)== True and pd.isnull(df.iloc[i].Tot_Day_Suply)== True and pd.isnull(df.iloc[i].Tot_Benes)== True:
        if(df.iloc[i].Fraud == 1):
            fraud_tot.append(i)
        else:
            nf_tot.append(i)

In [32]:
len(fraud_tot)

0

In [33]:
len(nf_tot)

0

## We see that the Tot_Benes is inconsistent with Tot so, we now check with every other column

### With Tot_Benes

In [36]:
fraud_ge6 = []
nf_ge6 = []
for i in range(len(df)):
    if pd.isnull(df.iloc[i].GE65_Tot_Clms)== True and pd.isnull(df.iloc[i].GE65_Tot_30day_Fills)== True and pd.isnull(df.iloc[i].GE65_Tot_Drug_Cst)== True and pd.isnull(df.iloc[i].GE65_Tot_Day_Suply)== True and pd.isnull(df.iloc[i].GE65_Tot_Benes)== True and pd.isnull(df.iloc[i].Tot_Benes):
        if(df.iloc[i].Fraud == 1):
            fraud_ge6.append(i)
        else:
            nf_ge6.append(i)

In [38]:
print(len(fraud_ge6))
print(len(nf_ge6))

97
66561

### Without Tot_Benes

In [39]:
fraud_ge6_wt = []
nf_ge6_wt = []
for i in range(len(df)):
    if pd.isnull(df.iloc[i].GE65_Tot_Clms)== True and pd.isnull(df.iloc[i].GE65_Tot_30day_Fills)== True and pd.isnull(df.iloc[i].GE65_Tot_Drug_Cst)== True and pd.isnull(df.iloc[i].GE65_Tot_Day_Suply)== True and pd.isnull(df.iloc[i].GE65_Tot_Benes)== True:
        if(df.iloc[i].Fraud == 1):
            fraud_ge6_wt.append(i)
        else:
            nf_ge6_wt.append(i)

In [40]:
print(len(fraud_ge6_wt))
print(len(nf_ge6_wt))

384
293722

In [58]:
ge6 = []
for i in range(len(df)):
    if pd.isnull(df.iloc[i].GE65_Tot_Clms)== True and pd.isnull(df.iloc[i].GE65_Tot_30day_Fills)== True and pd.isnull(df.iloc[i].GE65_Tot_Drug_Cst)== True and pd.isnull(df.iloc[i].GE65_Tot_Day_Suply)== True and pd.isnull(df.iloc[i].GE65_Tot_Benes)and pd.isnull(df.iloc[i].Tot_Benes)== True:
        ge6.append(i)

In [57]:
selected_columns = ["Tot_Benes","GE65_Tot_Clms","GE65_Tot_30day_Fills","GE65_Tot_Drug_Cst"]
df1_ge65 = df.drop(columns = selected_columns).copy().head(0)
df1_ge65 = pd.DataFrame(df1_ge65)
df1_ge65

Empty DataFrame
Columns: [PRSCRBR_NPI, Prscrbr_Type, Tot_Clms, Tot_30day_Fills, Tot_Drug_Cst, Tot_Day_Suply, GE65_Tot_Day_Suply, GE65_Tot_Benes, Brnd_Tot_Clms, Brnd_Tot_Drug_Cst, Gnrc_Tot_Clms, Gnrc_Tot_Drug_Cst, Othr_Tot_Clms, Othr_Tot_Drug_Cst, MAPD_Tot_Clms, MAPD_Tot_Drug_Cst, PDP_Tot_Clms, PDP_Tot_Drug_Cst, LIS_Tot_Clms, LIS_Drug_Cst, NonLIS_Tot_Clms, NonLIS_Drug_Cst, Opioid_Tot_Clms, Opioid_Tot_Drug_Cst, Opioid_Tot_Suply, Opioid_Tot_Benes, Opioid_LA_Tot_Clms, Opioid_LA_Tot_Drug_Cst, Opioid_LA_Tot_Suply, Opioid_LA_Tot_Benes, Antbtc_Tot_Clms, Antbtc_Tot_Drug_Cst, Antbtc_Tot_Benes, Antpsyct_GE65_Tot_Clms, Antpsyct_GE65_Tot_Drug_Cst, Antpsyct_GE65_Tot_Benes, Fraud]
Index: []

[0 rows x 37 columns]

In [ ]:
for i in ge6: